version: '3'
services:
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db-data:/data/db
  
  content-service:
    build:
      context: ./content-service
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - mongo-db
    environment:
      DATABASE_URL: mongodb://root:example@mongo-db:27017/contentServiceDB?authSource=admin

  interaction-service:
    build:
      context: ./interaction-service
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - mongo-db
    environment:
      DATABASE_URL: mongodb://root:example@mongo-db:27017/interactionServiceDB?authSource=admin

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - mongo-db
    environment:
      DATABASE_URL: mongodb://root:example@mongo-db:27017/userServiceDB?authSource=admin

volumes:
  mongo-db-data:
